{"name": "Проверка ошибки логина пользователя c невалидными значениями полей email, password", "status": "passed", "steps": [{"name": "Логинимся пользователем", "status": "passed", "parameters": [{"name": "email", "value": "'njbjgg'"}, {"name": "password", "value": "'gylbhz'"}], "start": 1713482900606, "stop": 1713482900942}], "parameters": [{"name": "email", "value": "'njbjgg'"}, {"name": "password", "value": "'gylbhz'"}], "start": 1713482900606, "stop": 1713482900943, "uuid": "5f27f6bd-c601-4360-be7a-c09d015ae197", "historyId": "1b97048f89f9276e0184e64719dfcaac", "testCaseId": "27215d35b8dd7ee84709190e39d85e77", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_with_invalid_credentials_return_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-VD1QDI3F4U5"}, {"name": "thread", "value": "14400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}